#!/bin/bash

SCRIPTS_DIR=$(dirname $(readlink -e "$0"))
ROOT_DIR=$(dirname "$SCRIPTS_DIR")
NOTEBOOKS_DIR="$ROOT_DIR/notebooks/statistics"
BUILD_DIR="$ROOT_DIR/output"

mkdir -p "$BUILD_DIR"
rm -f "$BUILD_DIR"/*.html

INDEX_HTML='<!DOCTYPE html>
<html>
<head>
  <title>Pageview analytics for “Mathe für Nicht-Freaks“</title>
</head>
<body>
<ul>'

for JUPYTER_NOTEBOOK in $(ls "$NOTEBOOKS_DIR"/*.ipynb); do
  JUPYTER_NOTEBOOK_BASENAME=$(basename "$JUPYTER_NOTEBOOK")
  JUPYTER_NOTEBOOK_BASENAME_NO_EXTENSION="${JUPYTER_NOTEBOOK_BASENAME%.ipynb}"
  HTML_FILE="$BUILD_DIR/$JUPYTER_NOTEBOOK_BASENAME_NO_EXTENSION.html"
  uv run jupyter nbconvert --to html "$JUPYTER_NOTEBOOK" --output "$HTML_FILE"
  INDEX_HTML="$INDEX_HTML
  <li><a href=\"$JUPYTER_NOTEBOOK_BASENAME_NO_EXTENSION.html\">$JUPYTER_NOTEBOOK_BASENAME</a></li>"
done

INDEX_HTML="$INDEX_HTML
</ul>
</body>
</html>"

echo "$INDEX_HTML" > "$BUILD_DIR/index.html"
