#!/bin/bash

SCRIPTS_DIR=$(dirname $(readlink -e "$0"))
ROOT_DIR=$(dirname "$SCRIPTS_DIR")
NOTEBOOK_DIR="$ROOT_DIR/notebooks"

TYPE="$1"

if [ "$TYPE" != "statistic" ] && [ "$TYPE" != "report" ]; then
    echo "Usage: create-new-notebook <TYPE> <NOTEBOOK_TITLE>" >&2
    echo "TYPE must be either 'statistic' or 'report'" >&2
    exit 1
fi

shift

NOTEBOOK_TITLE="$@"

YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY=$(date +%d)

# Convert the input string to lowercase, replace spaces with hyphens, and trim
# leading/trailing spaces or hyphens.
FILENAME=$(echo "$NOTEBOOK_TITLE" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '-' | sed 's/^[ \-]*//;s/[ \-]*$//')

# Define the notebook path
if [ "$TYPE" == "statistic" ]; then
    NOTEBOOK_PATH="$NOTEBOOK_DIR/statistics/$FILENAME.ipynb"
else
    NOTEBOOK_PATH="$NOTEBOOK_DIR/reports/$YEAR-$MONTH-$DAY-$FILENAME.ipynb"
fi

# Create the new jupyter notebook
cp "$NOTEBOOK_DIR/template-$TYPE.ipynb" "$NOTEBOOK_PATH"

# Replace the placeholders in the notebook
sed -i "s/NOTEBOOK_TITLE/$NOTEBOOK_TITLE/g" "$NOTEBOOK_PATH"
sed -i "s/YEAR/$YEAR/g" "$NOTEBOOK_PATH"

# Open the jupyter notebook
"$SCRIPTS_DIR/start-jupyter-lab" "$NOTEBOOK_PATH"
