name: Build and Publish

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Cache mfnf_cache
        uses: actions/cache@v4
        with:
          path: /tmp/mfnf_cache
          key: ${{ runner.os }}-mfnf_cache-${{ hashFiles('/tmp/mfnf_cache') }}
          restore-keys: |
            ${{ runner.os }}-mfnf_cache-

      - name: Build statistics
        run: ./scripts/build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  publish:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
